name: Text2SQL
description: "your_project_description"
author: "your_name"
date: "2026-01-17"
specification_version: 1.0
prototype_version: 1.0

environment_variables:
    # Added environment variables for Text-to-SQL models and database credentials
    OPENAI_CHAT_MODEL:
        default: "your_model_name"
        description: "OpenAI Chat Model to use for text-to-SQL conversion."
        required: true

    HR_USER:
        default: "your_username"
        description: "database username."
        required: true
    HR_PASSWORD:
        default: "your_password"
        description: "database password."
        required: true
    HR_DSN:
        default: "your_db_host:1521/your_db_name"
        description: "DB DSN."
        required: true

    BANK_USER:
        default: "your_username"
        description: "database username."
        required: true
    BANK_PASSWORD:
        default: "your_password"
        description: "database password."
        required: true
    BANK_DSN:
        default: "your_db_host:1521/your_db_name"
        description: "database DSN."
        required: true

    MUSIC_USER:
        default: "your_username"
        description: "database username."
        required: true
    MUSIC_PASSWORD:
        default: "your_password"
        description: "database password."
        required: true
    MUSIC_DSN:
        default: "your_db_host:1521/your_db_name"
        description: "database DSN."
        required: true

    WATERFALL_USER:
        default: "your_username"
        description: "database username."
        required: true
    WATERFALL_PASSWORD:
        default: "your_password"
        description: "database password."
        required: true
    WATERFALL_DSN:
        default: "your_db_host:1521/your_db_name"
        description: "database DSN."
        required: true

    CHUNK_SIZE:
        default: "your_chunk_size"
        description: "Chunk size for document processing."
        required: false
    CHUNK_OVERLAP:
        default: "your_overlap_size"
        description: "Chunk overlap for document processing."
        required: false

runtimes:
  - editor: JupyterLab
    kernel: Python 3.10
    edition: Standard

tasks:
  ## SESSION related AMP snippet
  - type: run_session
    name: Install Dependencies
    script: 0_session-install-dependencies/install_dependencies.py
    short_summary: Install Requirements and Dependencies
    kernel: python3
    cpu: 2
    memory: 4

  ## APPLICATION related AMP snippet
  - type: start_application
    name: Text2SQL
    short_summary: application for converting natural language queries into SQL commands.
    long_summary: This Text-to-SQL application is a comprehensive framework that converts natural language queries into SQL commands using a FastAPI backend and a Streamlit frontend, supported by a suite of utility scripts for indexing, prompt setup, and database interaction. The project is organized with dedicated directories for images and utility functions, and includes key configuration files like `.env` for model settings (using "gpt-4o-mini" and an OpenAI API key), multiple database credentials for HR, BANK, MUSIC, and WATERFALL databases, as well as a `config.yml` for project settings. It is designed for easy setup through a Python virtual environment and dependency installation via `requirements.txt`, with the backend running on Uvicorn and the frontend on Streamlit, all while adhering to industry-standard code quality practices with tools such as isort, flake8, and black.
    subdomain: chatbot
    script: 3_app-run-python-script/app.py
    environment_variables:
      TASK_TYPE: START_APPLICATION
